# Generated by Django 4.2.7 on 2024-02-01 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MailMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(max_length=150, verbose_name="Тема письма"),
                ),
                (
                    "text",
                    models.TextField(max_length=1024, verbose_name="Текст письма"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailing_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор сообщения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Письмо",
                "verbose_name_plural": "Письма",
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_start", models.DateField(verbose_name="Дата начала рассылки")),
                (
                    "date_finish",
                    models.DateField(verbose_name="Дата окончания рассылки"),
                ),
                (
                    "periodicity",
                    models.IntegerField(
                        choices=[
                            (0, "Ежедневно"),
                            (1, "Еженедельно"),
                            (2, "Ежемесячно"),
                        ],
                        default=0,
                        verbose_name="Периодичность рассылки",
                    ),
                ),
                (
                    "mailing_status",
                    models.IntegerField(
                        choices=[(0, "Создана"), (1, "Запущена"), (2, "Завершена")],
                        default=0,
                        verbose_name="Статус рассылки",
                    ),
                ),
                (
                    "mailing_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец рассылки",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailings",
                        to="app_mailing.mailmessage",
                        verbose_name="Рассылаемое сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
