# Generated by Django 4.2.7 on 2024-02-02 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_mailing", "0002_mailing_subscribers"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="attempts_count",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Количество попыток повторной отправки в случае неудачи",
                verbose_name="Число повторных попыток",
            ),
        ),
        migrations.CreateModel(
            name="MailingResend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempts_left",
                    models.IntegerField(
                        default=1, verbose_name="Оставшееся число попыток"
                    ),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_mailing.mailing",
                        verbose_name="Рассылка",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Получатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Повторная отправка",
                "verbose_name_plural": "Список писем для повторной отправки",
                "unique_together": {("mailing", "recipient")},
            },
        ),
    ]
