# Generated by Django 4.2.7 on 2024-02-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_mailing", "0003_mailing_attempts_count_mailingresend"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [("can_stop_mailing", "Может остановить рассылку")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterField(
            model_name="mailing",
            name="mailing_status",
            field=models.IntegerField(
                choices=[
                    (0, "Создана"),
                    (1, "Запущена"),
                    (2, "Завершена"),
                    (3, "Остановлена"),
                ],
                default=0,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
