# Generated by Django 4.2.7 on 2024-02-02 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_mailing", "0002_mailing_subscribers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_date_time",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время отчета"
                    ),
                ),
                (
                    "report_status",
                    models.IntegerField(
                        choices=[(0, "Успешно"), (1, "Предупреждение"), (2, "Ошибка")],
                        verbose_name="Статус операции",
                    ),
                ),
                (
                    "report_message",
                    models.CharField(max_length=500, verbose_name="Сообщение"),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="app_mailing.mailing",
                        verbose_name="Связанная рассылка",
                    ),
                ),
                (
                    "parent_report",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_reports",
                        to="app_logging.mailingreport",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Получатель сообщения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отчет рассылки",
                "verbose_name_plural": "Отчеты рассылок",
            },
        ),
    ]
