# Generated by Django 4.2.7 on 2024-02-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
        migrations.AlterField(
            model_name="user",
            name="comment",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Комментарий"
            ),
        ),
    ]
