# Generated by Django 4.2.7 on 2024-02-04 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_accounts", "0002_remove_user_first_name_remove_user_last_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [("can_block_users", "Может блокировать пользователей")]
            },
        ),
    ]
